[package]
name = "visualization"
version = "0.1.0"
edition = "2021"


[lib]
name = "visualization"
src = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.1"
thiserror = "1.0.37"
